version: '3.7'

services:
  phpmyadmin:
    container_name: rv_phpmyadmin
    build: ./docker/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '${PHPMYADMIN_PORT_80:-82}:80'
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    networks:
      - rv-app-network
