parameters:
    # General
    app.version: '0.1.0'
    app.name: 'RaceViz'
    app.twitter_handle: 'corcosoft'
    app.description: 'Just your usual web platform'
    app.keywords: 'web platform'
    app.mailer_from: Corcosoft <mailer@corcosoft.com>
    app.mailer_to: Borut <bobalazek124@gmail.com>
    app.roles:
        ROLE_USER: User
        ROLE_STAFF: Staff
        ROLE_MODERARATOR: Moderator
        ROLE_ADMIN: Admin
        ROLE_SUPER_ADMIN: Super Admin

    # Data
    app.vehicle_types:
        race: Race Vehicle
        safety: Safety Vehicle
    app.series:
        f1: Formula 1
        f2: Formula 2
        f3: Formula 3
        fe: Formula E
    app.tyres:
        hard: Hard (H)
        medium: Medium (M)
        soft: Soft (S)
        intermediate: Intermediate (I)
        wet: Wet (W)
        c1: Compound 1 (C1)
        c2: Compound 2 (C2)
        c3: Compound 3 (C3)
        c4: Compound 4 (C4)
        c5: Compound 5 (C5)
    app.race_driver_statuses:
        fin: Finished (FIN)
        dnf: DNF (Did Not Finish) / Retired
        dsq: DSQ/DQ (Disqualified)
        dns: DNS (Did Not Start/Show)
        dna: DNA (Did Not Arrive/Attend)
        dnq: DNQ (Did Not Qualify)
        dnpq: DNPQ (Did Not Pre-Qualify)
        dnp: DNP (Did Not Practice)
        ex: Excluded (EX)
        wd: Withdrawn (WD)
    app.race_incident_types:
        vehicle_collision: Vehicle Collision # between to cars
        vehicle_crash: Vehicle Crash # for example into a barrier
        vehicle_failure: Vehicle Failure
        other: Other
    app.race_flags:
        green: Green
        yellow: Yellow
        red: Red
        white: White
        black: Black
        chequered: Chequered

    # Credentials
    app.oauth.facebook:
        id: '%env(OAUTH_FACEBOOK_ID)%'
        secret: '%env(OAUTH_FACEBOOK_SECRET)%'
        version: '%env(OAUTH_FACEBOOK_VERSION)%'
        scope: '%env(OAUTH_FACEBOOK_SCOPE)%'
    app.oauth.google:
        id: '%env(OAUTH_GOOGLE_ID)%'
        secret: '%env(OAUTH_GOOGLE_SECRET)%'
    app.google.recaptcha.site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

    # TFA
    app.tfa.allowed_routes:
        - null # error
        - auth.logout
        - auth.login.tfa
