parameters:
    # General
    app.version: '0.1.0'
    app.name: 'RaceViz'
    app.twitter_handle: 'corcosoft'
    app.description: 'Just your usual web platform'
    app.keywords: 'web platform'
    app.mailer_from: Corcosoft <mailer@corcosoft.com>
    app.mailer_to: Borut <bobalazek124@gmail.com>
    app.roles:
        ROLE_USER: User
        ROLE_STAFF: Staff
        ROLE_MODERARATOR: Moderator
        ROLE_ADMIN: Admin
        ROLE_SUPER_ADMIN: Super Admin

    # Data
    app.series:
        F1: Formula 1
        F2: Formula 2
        F3: Formula 3
        FE: Formula E
    app.tyres:
        hard: Hard
        medium: Medium
        soft: Soft
        intermediate: Intermediate
        wet: Wet
    app.race_driver_statuses:
        f: Finished (F)
        dnf: DNF (Did Not Finish)
        dsq: DSQ (Disqualified)
        dns: DNS (Did Not Start)
        x: Excluded (X)

    # Credentials
    app.oauth.facebook:
        id: '%env(OAUTH_FACEBOOK_ID)%'
        secret: '%env(OAUTH_FACEBOOK_SECRET)%'
        version: '%env(OAUTH_FACEBOOK_VERSION)%'
        scope: '%env(OAUTH_FACEBOOK_SCOPE)%'
    app.oauth.google:
        id: '%env(OAUTH_GOOGLE_ID)%'
        secret: '%env(OAUTH_GOOGLE_SECRET)%'
    app.google.recaptcha.site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

    # TFA
    app.tfa.allowed_routes:
        - null # error
        - auth.logout
        - auth.login.tfa
